=== goldenforce/Git_Pull_Request/src/main/resource/def/SwiftDictionary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!---->
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Mike (Financial Technologies International) -->
<xs:schema targetNamespace="http://www.ftisoft.com/swift/dictionary" xmlns:sw="http://www.ftisoft.com/swift/dictionary" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="Field">
		<xs:sequence>
			<xs:element name="Description" type="xs:string" minOccurs="0"/>
			<xs:element name="SubField" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="required" type="xs:boolean" default="true"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="2"/>
					<xs:maxLength value="3"/>
					<xs:pattern value="\d\d\p{Lu}?"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="format" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="MsgField">
		<xs:choice minOccurs="0">
			<xs:element name="Qualifier" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="mandatory" type="xs:boolean" default="false"/>
					<xs:attribute name="repeating" type="xs:boolean" default="false"/>
					<xs:attribute name="name">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="4"/>
								<xs:maxLength value="4"/>
								<xs:pattern value="\p{Lu}\p{Lu}\p{Lu}\p{Lu}"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="Unqualified">
				<xs:complexType>
					<xs:attribute name="mandatory" type="xs:boolean" default="false"/>
					<xs:attribute name="repeating" type="xs:boolean" default="false"/>
				</xs:complexType>
			</xs:element>
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="Record">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="Record" type="sw:Record"/>
			<xs:element name="FieldChoice" type="sw:FieldChoiceType"/>
			<xs:element name="Field" type="sw:MsgField"/>
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="mandatory" type="xs:boolean" default="false"/>
		<xs:attribute name="repeating" type="xs:boolean" default="false"/>
	</xs:complexType>
	<xs:element name="Swift">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Fields" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Field" type="sw:Field" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
						<xs:attribute name="BusinessClass" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Message" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="Record" type="sw:Record"/>
							<xs:element name="FieldChoice" type="sw:FieldChoiceType"/>
							<xs:element name="Field" type="sw:MsgField"/>
						</xs:choice>
						<xs:attribute name="type" type="xs:string" use="required"/>
						<xs:attribute name="name" type="xs:string"/>
						<xs:attribute name="business" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="UniqueFieldName">
			<xs:selector xpath="sw:Fields/sw:Field"/>
			<xs:field xpath="@name"/>
		</xs:unique>
		<xs:keyref name="FieldIsValid" refer="sw:UniqueFieldName">
			<xs:selector xpath="sw:Message/sw:Field | sw:Message/*/sw:Field | sw:Message/*/*/sw:Field | sw:Message/*/*/*/sw:Field | sw:Message/*/*/*/*/sw:Field"/>
			<xs:field xpath="@name"/>
		</xs:keyref>
	</xs:element>
	<xs:complexType name="FieldChoiceType">
		<xs:sequence>
			<xs:element name="Qualifier" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="mandatory" type="xs:boolean" default="false"/>
					<xs:attribute name="repeating" type="xs:boolean" default="false"/>
					<xs:attribute name="options" type="xs:string" use="required"/>
					<xs:attribute name="name">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="4"/>
								<xs:maxLength value="4"/>
								<xs:pattern value="\p{Lu}\p{Lu}\p{Lu}\p{Lu}"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="Field" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
</xs:schema>

=== goldenforce/Git_Pull_Request/src/main/resource/def/SwiftDataDictionary.xml
<?xml version="1.0" encoding="UTF-8"?>
<Swift xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ftisoft.com/swift/dictionary SwiftDictionary.xsd" xmlns="http://www.ftisoft.com/swift/dictionary" xmlns:sw="http://www.ftisoft.com/swift/dictionary">
	<Fields BusinessClass="Currency">
		<Field format=":4!c//3!a" name="11A">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Currency Code" required="true"/>
		</Field>
	</Fields>
	<Fields BusinessClass="Type of Related Financial Instrument">
		<Field format=":4!c/[4!c[4c]]/30z" name="12A">
			<SubField name="Qualifier" required="true"/>
			<SubField name="DataSourceScheme" required="false"/>
			<SubField name="InstrumentCodeorDescription" required="true"/>
		</Field>
		<Field format=":4!c/[4!c[4c]]/4!c" name="12B">
			<SubField name="Qualifier" required="true"/>
			<SubField name="DataSourceScheme" required="false"/>
			<SubField name="Instrument Code" required="true"/>
		</Field>
		<Field format=":4!c//6!c" name="12C">
			<SubField name="Qualifier" required="true"/>
			<SubField name="CFICode" required="true"/>
		</Field>
	</Fields>
	<Fields BusinessClass="Number Identification">
		<Field format=":4!c//3!c" name="13A">
			<SubField name="Qualifier" required="true"/>
			<SubField name="NumberIdentification" required="true"/>
		</Field>
		<Field format=":4!c/[4!c[4c]]/30z" name="13B">
			<SubField name="Qualifier" required="true"/>
			<SubField name="DataSourceScheme" required="false"/>
			<SubField name="Number" required="true"/>
		</Field>
		<Field format=":4!c//4!c" name="13F">
			<SubField name="Qualifier" required="true"/>
			<SubField name="NumberIdentification" required="true"/>
		</Field>
		<Field format=":4!c//4!n" name="13G">
			<SubField name="Qualifier" required="true"/>
			<SubField name="NumberIdentification" required="true"/>
		</Field>
		<Field format=":4!c//2!n" name="13H">
			<SubField name="Qualifier" required="true"/>
			<SubField name="NumberIdentification" required="true"/>
		</Field>
		<Field format=":4!c//8c" name="13I">
			<SubField name="Qualifier" required="true"/>
			<SubField name="NumberIdentification" required="true"/>
		</Field>
	</Fields>
	<Fields BusinessClass="Start of Block">
		<Field format="16c[/3!n[/3!n]]" name="16R">
			<SubField name="StartofBlock" required="true"/>
			<SubField name="NumberofOccurences" required="false"/>
			<SubField name="Total NumberofOccurences" required="false"/>
		</Field>
	</Fields>
	<Fields BusinessClass="End of Block">
		<Field format="16c[/3!n]" name="16S">
			<SubField name="EndofBlock" required="true"/>
			<SubField name="NumberofOccurences" required="false"/>
		</Field>
	</Fields>
	<Fields BusinessClass="Flag">
		<Field format=":4!c//1!a" name="17B">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Flag" required="false"/>
		</Field>
	</Fields>
	<Fields BusinessClass="Amount">
		<Field format=":4!c//[s]3!a15d" name="19A">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Sign" required="false"/>
			<SubField name="CurrencyCode" required="true"/>
			<SubField name="Amount" required="true"/>
		</Field>
		<Field format=":4!c//3!a15d" name="19B">
			<SubField name="Qualifier" required="true"/>
			<SubField name="CurrencyCode" required="true"/>
			<SubField name="Amount" required="true"/>
		</Field>
		<Field format=":4!c//[s]3!a17d" name="19C">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Sign" required="false"/>
			<SubField name="CurrencyCode" required="true"/>
			<SubField name="Amount" required="true"/>
		</Field>
	</Fields>
	<Fields BusinessClass="Reference">
		<Field format="16x" name="20">
			<Description>Transaction Reference Number</Description>
			<SubField name="Reference" required="true"/>
		</Field>
		<Field format=":4!c//16z" name="20C">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Reference" required="true"/>
		</Field>
		<Field format=":4!c//25z" name="20D">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Reference" required="true"/>
		</Field>
	</Fields>
	<Fields BusinessClass="Indicator">
		<Field format=":4!c/[4!c[4c]]/4!c" name="22F">
			<SubField name="Qualifier" required="true"/>
			<SubField name="DataSourceScheme" required="false"/>
			<SubField name="Indicator" required="true"/>
		</Field>
		<Field format=":4!c//4!c" name="22H">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Indicator" required="true"/>
		</Field>
	</Fields>
	<Fields BusinessClass="Function of the Message">
		<Field format="4!c[/4!c]" name="23G">
			<SubField name="Function" required="true"/>
			<SubField name="SubFunction" required="false"/>
		</Field>
	</Fields>
	<Fields BusinessClass="Reason Code">
		<Field format=":4!c/[4!c[4c]]/4!c" name="24B">
			<SubField name="Qualifier" required="true"/>
			<SubField name="DataSourceScheme" required="false"/>
			<SubField name="ReasonCode" required="true"/>
		</Field>
	</Fields>
	<Fields BusinessClass="Status Code">
		<Field format=":4!c/[4!c[4c]]/4!c" name="25D">
			<SubField name="Qualifier" required="true"/>
			<SubField name="DataSourceScheme" required="false"/>
			<SubField name="StatusCode" required="true"/>
		</Field>
	</Fields>
	<Fields BusinessClass="Page Number / Continuation Indicator">
		<Field format="5n/4!c" name="28E">
			<SubField name="PageNumber" required="true"/>
			<SubField name="ContinuationIndicator" required="true"/>
		</Field>
	</Fields>
	<Fields BusinessClass="Identification of a Security">
		<Field format="[ISIN1!e12!c]&#x0a;[5*35z]" name="35B">
			<SubField name="IdentificationofaSecurity" required="false"/>
			<SubField name="DescriptionoftheSecurity-Line1" required="false"/>
		</Field>
		<Field format="12!c" name="35I">
			<SubField name="ISIN" required="true"/>
		</Field>
		<Field format="2!a/4!c/30z" name="35J">
			<SubField name="CountryCode" required="true"/>
			<SubField name="NumberingAgencyCode" required="true"/>
			<SubField name="LocalCode" required="true"/>
		</Field>
	</Fields>
	<Fields BusinessClass="Quantity of Financial Instrument">
		<Field format=":4!c//4!c/15d" name="36B">
			<SubField name="Qualifier" required="true"/>
			<SubField name="QuantityTypeCode" required="true"/>
			<SubField name="Quantity" required="true"/>
		</Field>
		<Field format=":4!c//4!c" name="36C">
			<SubField name="Qualifier" required="true"/>
			<SubField name="QuantityCode" required="true"/>
		</Field>
		<Field format=":4!c//4!c/17d" name="36D">
			<SubField name="Qualifier" required="true"/>
			<SubField name="QuantityTypeCode" required="true"/>
			<SubField name="Quantity" required="true"/>
		</Field>
        <Field format=":4!c//4!c/[s]16d" name="36E">
			<SubField name="Qualifier" required="true"/>
			<SubField name="QuantityTypeCode" required="true"/>
            <SubField name="Sign" required="false"/>
			<SubField name="Quantity" required="true"/>
	    </Field>
	</Fields>
	<Fields BusinessClass="Period">
		<Field format=":4!c//8!n/8!n" name="69A">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Date" required="true"/>
		</Field>
		<Field format=":4!c//8!n6!n/8!n6!n" name="69B">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Date" required="true"/>
			<SubField name="Time" required="true"/>
			<SubField name="Date" required="true"/>
			<SubField name="Time" required="true"/>
		</Field>
		<Field format=":4!c//8!n/4!c" name="69C">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Date" required="true"/>
			<SubField name="DateCode" required="true"/>
		</Field>
		<Field format=":4!c//8!n6!n/4!c" name="69D">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Date" required="true"/>
			<SubField name="Time" required="true"/>
			<SubField name="DateCode" required="true"/>
		</Field>
		<Field format=":4!c//4!c/8!n" name="69E">
			<SubField name="Qualifier" required="true"/>
			<SubField name="DateCode" required="true"/>
			<SubField name="Date" required="true"/>
		</Field>
		<Field format=":4!c//4!c/8!n6!n" name="69F">
			<SubField name="Qualifier" required="true"/>
			<SubField name="DateCode" required="true"/>
			<SubField name="Date" required="true"/>
			<SubField name="Time" required="true"/>
		</Field>
		<Field format=":4!c//8!n6!n/8!n6!n" name="69H">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Date" required="true"/>
			<SubField name="Time" required="true"/>
			<SubField name="Date" required="true"/>
			<SubField name="Time" required="true"/>
		</Field>
		<Field format=":4!c//4!c/8!n6!n" name="69I">
			<SubField name="Qualifier" required="true"/>
			<SubField name="DateCode" required="true"/>
			<SubField name="Date" required="true"/>
			<SubField name="Time" required="true"/>
		</Field>
		<Field format=":4!c//4!c" name="69J">
			<SubField name="Qualifier" required="true"/>
			<SubField name="DateCode" required="true"/>
		</Field>
	</Fields>
	<Fields BusinessClass="Narrative">
		<Field format=":4!c//4*35z" name="70C">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Narrative" required="true"/>
		</Field>
		<Field format=":4!c//6*35z" name="70D">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Narrative" required="true"/>
		</Field>
		<Field format=":4!c//10*35z" name="70E">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Narrative" required="true"/>
		</Field>
		<Field format=":4!c//8000z" name="70F">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Narrative" required="true"/>
		</Field>
		<Field format=":4!c//variable length" name="70G">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Narrative" required="true"/>
		</Field>
		<Field format=":4!c//35z" name="70H">
			<SubField name="Qualifier" required="true"/>
			<SubField name="Narrative" required="true"/>
		</Field>
	</Fields>
	<Fields BusinessClass="Price">
		<Field format=":4!c//4!c/15d" name="90A">
